name: Elixir CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        elixir: [1.17.3, 1.18.0, 1.18.1, 1.18.2]
        otp: [25.0, 26.0, 27.0]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}

    - name: Retrieve Cached Dependencies
      uses: actions/cache@v4
      id: mix-cache
      with:
        path: |
          deps
          _build
          priv/plts
        key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-

    - name: Install dependencies
      if: steps.mix-cache.outputs.cache-hit != 'true'
      run: mix deps.get

    - name: Compile dependencies
      if: steps.mix-cache.outputs.cache-hit != 'true'
      run: mix deps.compile

    - name: Run tests
      run: mix test

    - name: Check Code Format
      run: mix format --check-formatted

    - name: Run Credo
      run: mix credo 
